### ISSUE TITLE
Coastal Sandbox Sagemaker Notebook image repo

### ISSUE THREAD

**Issue by mykelalvis** [ioos/governance#10]
### Repository name

ioos-sagemaker-notebook-container

### Repository purpose

Repo to build and release-manage containers for Sagemaker notebooks on the coastal sandbox.

The name can be modified if needed.  It's not really used for any sort of released artifact.

### Repository description

CI build and release-managed containers for Sagemaker notebooks on the coastal sandbox

### Repository type

Public

### Repository license

BSD 3-Clause

### Repository options

- [ ] Add a README.md file
- [ ] Add a .gitignore file

### Specify GitHub usernames or IOOS GitHub Team for repository access

ioos/modeling **Maintain**

**Comment by mwengren** [comment]
Repo created: https://github.com/ioos/cloud-sandbox-sagemaker.

I modified the name slightly to make the relationship to existing cloud-sandbox more clear.
