### ISSUE TITLE
SoundCoop

### ISSUE THREAD

**Issue by carriecwall** [ioos/governance#4]
### Repository name

soundcoop

### Repository purpose

SoundCoop is an IOOS DMAC project funded in 2021. As part of the project's deliverable and service to the IOOS community, we will publish several Jupyter Notebooks to increase understanding of how to create standardized passive acoustic monitoring metrics and additional applications of those standardized products.

### Repository description

This repository contains Jupyter notebooks developed by the passive acoustic community for the SoundCoop project.

### Repository type

Public

### Repository license

BSD 3-Clause

### Repository options

- [X] Add a README.md file
- [ ] Add a .gitignore file

**Comment by MathewBiddle** [comment]
I do recommend that we add at least one notebook to the IOOS CodeLab https://ioos.github.io/ioos_code_lab/content/intro.html (GitHub repo: https://github.com/ioos/ioos_code_lab). If the project is only generating a few notebooks, we could simply add them to the IOOS CodeLab and not have a separate repo.

In the end I'm okay with creating a new repo for this activity, but we should consider if the CodeLab fills the need.

**Comment by mwengren** [comment]
Agree with that @MathewBiddle.  I think the expected number of notebooks probably is the critical factor.  I'd lean towards building the CodeLab myself.  

Down the road, we could consider restructuring the side menu in the CodeLab to be more topical vs function-based.  Or if there's a way to index by both function (Data Access) and project/topic area (SoundCoop) without becoming too cluttered.  What's really needed is a keyword/tagging option for notebook discovery...

**Comment by MathewBiddle** [comment]
The repository has been created. See https://github.com/ioos/soundcoop

I have created a new GitHub team @ioos/pamdata (https://github.com/orgs/ioos/teams/pamdata) and given that team maintenance privilege's to the ioos/soundcoop repo.   @carriecwall, I have sent you an invite to the team and I will make you the maintainer of that team so you can add whomever to the team as appropriate.  

You can learn more about repository roles at https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization.
