### ISSUE TITLE
Create repository for SantuaryWatch ioos.us website development and documentation

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/governance#6]
### Repository name

sanctuarywatch-webpage

### Repository purpose

In collaboration with NMS we are working on a WordPress migration of the https://sanctuarywatch.ioos.us/ website. Currently, we do not have a landing page GitHub repository for the sanctuarywatch landing page. As sanctuary staff will be developing the WordPress plug-ins and associated documentation for the website, this would be a good place to store the plug-ins and write the deployment documentation. 

Following some ideas we've had to have a repository in the ioos organization for each of our ioos.us site, I am requesting we add one for this effort. 

Other ioos.us websites/landing pages that have GitHub repositories:
* https://github.com/ioos/atn-dac
* https://github.com/ioos/gliders
* https://github.com/ioos/hfradar-dac-landing
* https://github.com/ioos/comt-landing
* https://github.com/ioos/ioos_code_lab
* https://github.com/ioos/osmc
* https://github.com/ioos/ocean-acidification

cc: @superjai, @nguyandy

P.S. The repository name was a shot in the dark. If we have some common naming convention for these ioos.us sites, lets follow that.

### Repository description

WordPress documentation and plug-ins for the National Marine Santuaries web-enabled Condition Reporting (WebCR) website sanctuarywatch.ioos.us.

### Repository type

Public

### Repository license

Creative Commons Zero v1.0 Universal

### Repository options

- [X] Add a README.md file
- [X] Add a .gitignore file

**Comment by MathewBiddle** [comment]
@mwengren any major issues if we create a repo for this effort? If not, do you have a preference for a naming schema?

**Comment by mwengren** [comment]
@MathewBiddle we don't seem to really have a naming convention, but despite that, we don't really use -webpage as a suffix in any other cases.  The closest I can see to a pattern is that we just name the repo to match the DNS subdomain (gliders -> gliders.ioos.us, osmc -> osmc.ioos.us).  

So I guess my preference is to just call it 'sanctuarywatch' if that's the planned domain name.

Hopefully, a few of the static 'landing page' repos can be retired in the future if we can find a path forward to consolidate the RPS-managed ioos.us sites (comt-landing, gliders, hfradar-dac-landing, osmc, ocean-acidification) under the [ioos-us repo](https://github.com/ioos/ioos-us), perhaps.

**Comment by MathewBiddle** [comment]
`sanctuarywatch` is the planned domain name, so let's go with that. I'll close this issue once the repo is created.

**Comment by MathewBiddle** [comment]
https://github.com/ioos/sanctuarywatch
