### ISSUE TITLE
Marine Life Data Network planning/execution

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/governance#7]
### Repository name

marine_life_data_network

### Repository purpose

Planning efforts relevant to IOOS Marine Life and IOOS DMAC.

### Repository description

Planning and executing marine life efforts.

### Repository type

Public

### Repository license

BSD 3-Clause

### Repository options

- [X] Add a README.md file
- [X] Add a .gitignore file

### Specify GitHub usernames or IOOS GitHub Team for repository access

mathewbiddle

**Comment by MathewBiddle** [comment]
add some capacity to gather requirements / user needs

**Comment by MathewBiddle** [comment]
Some questions I would like to answer before we proceed:

- [ ] Should this simply be a repository to log issues for project management?
- [ ] Should we use a [project board](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)?
- [ ] What might be put in the repository?
- [ ] I would like this to be a place where we can gather requirements. Can we use [GitHub issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) to do this?

**Comment by MathewBiddle** [comment]
@laurabrenskelle any thoughts on the above questions? I think we can start with a blank slate and work from there...

Mainly I'm curious about the name of the repo `marine_life_data_network`. Does that make sense?

url would be https://github.com/ioos/marine_life_data_network

**Comment by laurabrenskelle** [comment]
I think the name seems fine.

I could envision using this repo to work on notebooks related to marine life data synthesis and biodiversity variables. But also to track issues for data or project management. What other things are you thinking might go in this repo?

A project board would be interesting to start and see if we find it helpful. I think it might be easier to start with the project board as part of the workflow than to try to implement it later. Possibly the Roadmap and/or a Kanban style project board? I could see the Roadmap one being useful to plan future work, and the Kanban version as useful for tracking work in progress.

**Comment by MathewBiddle** [comment]
@laurabrenskelle I've been thinking... What different purpose would this marine life repo serve, that https://github.com/ioos/mbon-docs is not serving now? I'd really like to get away from categorizing the DMAC work we are doing as "MBON". Instead it **is** IOOS Marine Life. Maybe we should just rename that repository?

If we do a rename to the repository, what happens to the ioos.github.io/mbon-docs website? What would need to change and where?

I think the project board could be added and referenced to from any repository?

**Comment by laurabrenskelle** [comment]
True, I think IOOS Marine Life is bigger than just MBON, though the MBON projects are part of it. Are RAs doing marine life monitoring/observing that is not part of an MBON project? Are there other marine life observations we're missing by focusing on MBON? I see your point that any marine life observation work could just as easily use the same information as the mbon-docs. Maybe that should become marinelife-docs to serve as a one stop shop for how to share marine life observations with NOAA/IOOS/NCEI and OBIS?

I know MBON is trying to think about synthesis, but I think that is really key to IOOS Marine Life. The reason IOOS Marine Life is not just another data access portal for marine observations is that it is intended to offer actionable information about species distributions, trends, and indicators relating to essential variables to stakeholders in policymaking and conservation. I think having a dedicated repo/space to discuss what this looks like with folks from NMFS, ONMS, etc. might be helpful.

And yes, my understanding is that GitHub project boards can include issues from different repositories, not just the one it was made under.

**Comment by MathewBiddle** [comment]
created **https://github.com/ioos/marine_life_data_network**
