### ISSUE TITLE
Create new repo for HFRNet migration

### ISSUE THREAD

**Issue by dpsnowden** [ioos/governance#8]
### Repository name

hfrnet

### Repository purpose

This repo should be the main source of technical documentation and project planning for migrating the HFRNet data assembly function from SIO/CORDC to a new host in NOAA.  The design for the new system is evolving, and this repo should be a place to collect requirements (ISSUE_TEMPLATE) and map out a roadmap and development plan.  Whether this repo also is the place for some/all/none of the code is something to be decided.  

This repo should support the ioos.github.io static site generation workflow.  

Probably need an internal meeting to decide some of the details.  License?  Team access?  Github Actions etc.

### Repository description

Technical documentation and code for the HFRNet data assembly center supported by U.S. IOOS.  

### Repository type

Public

### Repository license

BSD 3-Clause

### Repository options

- [X] Add a README.md file
- [X] Add a .gitignore file

### Specify GitHub usernames or IOOS GitHub Team for repository access

ioos/ioos-github-io Maintain site.

**Comment by MathewBiddle** [comment]
@dpsnowden Thanks for this request! 

We might want to think about creating an hfrnet GitHub team under the IOOS organization. @Zelenke could have elevated privileges to manage the team.

Otherwise, I'm okay with creating this repo. @mwengren see any issues?

**Comment by dpsnowden** [comment]
@MathewBiddle I'll defer to you on the best way to manage permissions.

**Comment by mwengren** [comment]
Just a few comments.  

Are we decided on a name for the HFRNet 2.0?  I've seen HFR DAC and HFRNet both used in the project so far.   Not a show stopper at all - we can change the name at any point.  

If it's going to be mainly for ioos.github.io documentation purposes to start with, the easiest way to do that would be to use the [jekyll skeleton/template](https://github.com/ioos/ioos-documentation-jekyll-skeleton) to create the new repo.    Just click the 'Use this template' button - not sure who should do that but if this sounds like a good plan I think any of us can go ahead.

**Comment by mwengren** [comment]
To start with for permissions, we can use this team: https://github.com/orgs/ioos/teams/ioos-github-io.

And probably add @dpsnowden to it as well.

**Comment by Zelenke** [comment]
@mwengren My vote for a name is to just keep using "HFRNet".  I'm thinking that will avoid people having to learn a new name/acronym, cutting down on potential confusion.

**Comment by MathewBiddle** [comment]
https://github.com/ioos/hfrnet

**Comment by MathewBiddle** [comment]
added @dpsnowden to https://github.com/orgs/ioos/teams/ioos-github-io

**Comment by MathewBiddle** [comment]
Since we started from the jekyll skeleton, we have a website up and running https://ioos.github.io/hfrnet/

Content needs to be updated, of course. @Zelenke we have a how to guide on using the IOOS Jekyll documentation skeleton [here](https://ioos.github.io/ioos-documentation-jekyll-skeleton/howto.html). Let us know if that has enough information to get you started.

I think we can close this now. Thanks all!
